project:
  type: book
  output-dir: docs

profile:
  default: all

book:
  title: "Expressions of Community"
  subtitle: "Understanding Variations in Community through LGBTQ Experiences"
  author: "Connor Gilroy"
  date: today
  date-format: "MM/DD/YYYY"
  output-file: "gilroy-expressions-of-community"
  repo-url: https://github.com/ccgilroy/dissertation/
  repo-actions: [edit, issue]
  downloads: [pdf]
  # chapters:
  #   - index.qmd
  #   - intro.qmd
  #   - discourse.qmd
  #   - place.qmd
  #   - networks.qmd
  #   - conclusion.qmd
  #   - references.qmd

bibliography: references.bib
csl: american-sociological-association.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    fontsize: 12pt
    include-in-header:
      text: |
        \usepackage{footmisc}
    include-before-body: before.tex
