project:
  type: book
  output-dir: docs

book:
  title: "Expressions of Community"
  author: "Connor Gilroy"
  date: "1/13/2023"
  repo-url: https://github.com/ccgilroy/dissertation/
  repo-actions: [edit, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - place.qmd
    - discourse.qmd
    - networks.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib
csl: american-sociological-association.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    fontsize: 12pt
    include-in-header:
      text: |
        \usepackage{footmisc}
    include-before-body: before.tex
