# Acknowledgments {.unnumbered .unlisted}

This dissertation owes a great deal to many, many people. No one can do a PhD alone. First, I would like to thank my advisor and chair, Kate Stovel, for years of intellectual conversations and support, and especially for motivation during the final sprint to the end. I would like to thank Jelani Ince for his encouragement and willingness to jump in so soon after joining the UW sociology department, which is extraordinarily lucky to have him. I am grateful to Kyle Crowder for his generous feedback, always pushing me toward greater conceptual and theoretical clarity. I thank Mako Hill for being an enthusiastic Graduate School Representative and for graciously inviting me to participate alongside the Community Data Science Collective on occasion. It's always powerful and meaningful to see intellectual community in action.

The various chapters of this dissertation benefited from varied and diverse intellectual support. For Chapter 2, I thank Avery Dame-Griff for sharing code and advice for working with Usenet archives, and Steve Goodreau for the suggestion to look more closely at soc.motss. Previous versions of Chapter 2 also received generous feedback from the Community Data Science Collective and the Metaphors and Meaning roundtable at ASA 2021. I thank Greggor Mattson for reading Chapter 3 and providing much-needed encouragement at a crucial moment, and the Inter-university Consortium for Political and Social Research, especially Kelly Ogden-Schuette, for facilitating access to geocoded survey data. I also thank Mahesh Somashekhar for inviting me to present Chapter 3 on the Queer Placemaking panel at ASA 2022. For Chapter 4, I thank Nate TeBlunthuis and Ian Kennedy for technical and theoretical advice on how to work with Reddit data and make thoughtful use of word embeddings. Throughout, the TechnoSoc writing group provided a valuable virtual space for focusing on this work.

Personally, I thank my mom, for being the strongest person I know; my dad, for always being there to pick up the phone and chat; and my sister, for fighting to make our hometown a more vibrant, colorful place.

Lastly, I would not have made it this far without support from queer communities here in Seattle. Thank you, to all of you. To Lincoln, Kyle, Kai, and the rest of the queers of the Hill, for showing me what real community can feel like. To Kince, for your tireless work building community for Seattle Gaymers and beyond. To Maarten and Oliver, for your support from afar. To Nick, for more than a decade of friendship. To S&B, for making my life more interesting when you were a part of it. And finally, to Jason, for long walks with the dog and unrepayable debts.
