# Conclusion

## Summary

This dissertation set out to investigate how structural features -- social density of interactions, physical density of proximity, abundance of others with shared group characteristics -- create the conditions for the existence of a community. It connects those contextual features to how LGBTQ individuals outwardly express and subjectively experience community, through their language, group participation, and self-reports of belonging.

Chapter 2 showed that not only does the discourse in the soc.motss Usenet group, an early virtual community, use "community" in the sense of *Gemeinschaft* to at least an equal extent as generic English-language text, it also deemphasizes the geographic aspects of community and replaces that with connotations specific to LGBTQ identities. This strongly implies that LGBTQ community is foregrounded, not backgrounded, in a self-selected virtual community that is densely organized around that identity category.

Chapter 3 showed that small-area abundance of same-sex couples, and to a lesser extent overall density, is associated with greater sense of community connectedness for LGBQ people. Associations weaken or disappear at a larger spatial scale. The key finding is consistent with the idea that contextual features that make access to community easier heighten the experience of it rather than leading it to be taken for granted, and not consistent with the idea that places with less access (and presumably more stigma and marginalization) lead people to seek out and accordingly report more of a connection to community. These results imply that community does not generally recede into the background in the places where access to LGBTQ people and institutions would be most abundant, nor does it take on extra salience in more peripheral places.

Chapter 4 showed significant heterogeneity in the relationship between interaction network centrality and expressions of community talk in a set of 11 LGBTQ groups on Reddit, a virtual platform. In the largest and most general subreddits, centrality is associated with explicit mentions of community, and to a lesser extent with the implicit distance measure as well. In other cases the association is reversed or absent. The cases with positive associations support the idea that central actors' embeddedness is reflected in their language as well. This work implies that, if these 11 ostensibly similar groups differ in their patterns, there is no universal relationship between community-oriented language and embeddedness in group interactions. A second, methodological implication is that applying a text analysis tool to a substantive use case with a wide variety of text can reveal shortcomings of the method that might not otherwise be apparent; this weighs into a debate between simpler and more complex approaches to text analysis in computational sociology.

## Contributions

Overall, this work demonstrates how community can be built around a particular marginalized identity. Each chapter investigates the relationship between structural features that facilitate social proximity and how LGBTQ people outwardly express and subjectively experience community and belonging. It could have been the case that expressions of community stood in for structural elements that promote belonging, that community would be ambient and relegated to the background in those contexts. That would have gone hand-in-hand with a sense of outsiderness pushing LGBTQ individuals to seek out community most saliently in contexts of stigma, marginalization, and scarcity.

Instead, across this work, I find that experiences of community are most intense and expressions of community most frequent, not for peripheral members of LGBTQ communities but for the most central. This core finding might appear relatively conventional, not counterintuitive. But queer communities are an unusual phenomenon, both built around a core social identity, but also something almost no LGBTQ individual is born or raised with intrinsic access to. That lack of rootedness might have translated into LGBTQ community arising mainly from transient sites like ephemeral queer pop-ups [@stillwagon_queer_2019] or fleeting queer counterpublics [@berlant_sex_1998], rather than the durable contextual characteristics I observe. Nor do I find signs of rejection or ambivalence toward LGBTQ community in the contexts where access is most abundant, as some qualitative researchers have [@brown-saracino_how_2017; @winer_solidarity_2020]. Where community for LGBTQ people is most readily available, it turns out to be highly valued rather than passé. The attractive force of community arises from something more than stigma.

Attaining these substantive insights required methodological innovations, a contribution on their own. Most studies of community, especially of LGBTQ communities, are qualitative [e.g., @orne_boystown_2017; @brown-saracino_how_2017; @forstie_theory_2020]; I chose to complement these detailed studies with the breadth afforded by quantitative methods. Linking structural features to expressive and subjective outcomes required stitching together diverse data sources and triangulating across contexts, which gives my results spatial representativeness and temporal breadth. Most notably, I adapted natural language process techniques for computational text analysis to delve into the specific meaning of "community" as a complex, ambiguous concept with a rich social life beyond the academy.  To lay the groundwork for interpreting my subsequent, more straightforward studies, linking community both to the social organization of *Gemeinschaft* and to LGBTQ identities was a necessary innovation.

## Limitations

This dissertation is not without its limitations. The empirical results, while largely pointing toward community as foregrounded and central rather than backgrounded and ambient, do contain mixed signals. This is most apparent in the varied results from different LGBTQ groups on Reddit in Chapter 4. In addition, the spatial patterns in Chapter 3 are not entirely consistent with qualitative work finding between-place heterogeneity, most notably ambient community in places like Ithaca, New York [@brown-saracino_how_2017]. This points toward a fundamental limitation of a partial and triangulated approach -- I am unable to observe any one context fully. A comprehensive view would instead measure locations, interactions, expressions, and subjective experiences for the same people in the same groups. With that level of detail, heterogeneity between communities, rather than common patterns among them, might come into view.

This work is a broad examination of fundamentally dynamic processes that are hard to model. If structural density and embeddedness leads to subjective and expressive forms of community belonging, and these in turn promote proximity, connection, and interaction, then this feedback loop is difficult to disentangle. Some of this is micro-scale, unfolding at the level of repeated participation in group conversations and activities; future work might investigate the fine-grained temporality that forms and sustains LGBTQ spaces and groups. Some of this unfolds at the temporal scale of entire lifetimes, as LGBTQ people with the motivation and means self-select into places where they hope to find belonging; following LGBTQ individuals across the life course as they migrate and make other key life choices might show how central LGBTQ community can be for life trajectories. 

The entwined nature of the factors influencing community limits the concepts I am able to operationalize. While I operationalize signs of density, abundance, and embeddedness, those factors obscure the role of heterogeneity, diversity, and inclusivity. Empirically, I found these two sets of attributes to be too correlated to disentangle. Theoretically, I continue to believe inclusivity is important as one of the key features of some queer spaces, and absolutely essential for understanding the moral boundaries of LGBTQ community [@vaisey_structure_2007; @meyer_differences_2020]. 

While my data span two decades and multiple sites, they do not automatically generalize to all times and places. The survey data in Chapter 3 are only from the contemporary United States. While virtual communities like those I analyze in Chapter 2 and Chapter 4 have the potential for international reach, they are still U.S.-centric [@rheingold_virtual_2000]. As in much NLP-based work, the textual data I rely on are English-only [@bender_achieving_2011]; analogues to "community" might not have the same resonances in other languages. Indeed, in a language as closely related to English as French, "community" is hard to translate [@anderson_imagined_2016]. Fundamentally, it is strange to study place attachment in the context of a settler-colonial society, or to study community talk in a colonially imposed and globally hegemonic language; I do not adequately address that dissonance in this work.

## Future directions

I close by considering the future of studying LGBTQ communities, and the future of those queer communities themselves. First, new empirical findings might arise from engaging innovative data sources. Digitized archives like the *Mapping the Gay Guides* project [@regan2019a] increasing offer the opportunity to link 
historical trajectories of LGBTQ spaces with the present. More recent virtual platforms than Reddit, like Discord [@jiang_moderation_2019], offer new sites of queer community building for study. Second, key research questions can be drawn from what this dissertation leaves unanswered. Novel quantitative research methods are need to understand how not just shared identity and discourse, but shared activities and practices [@brint_gemeinschaft_2001; @orne_boystown_2017], contribute to community. Finally, as I alluded to above, I hypothesize that inclusivity plays an important role in queer spaces as a value and a practice. Anarchic and accepting does not mean incohesive; instead, it might be a positive, normative vision of the world, a foundation for collective action rather than a demobilizing force. As they say, Stonewall -- the central event of queer collective memory [@armstrong_movements_2006] -- was a riot.

Since I began this project, times have changed for digital and computational research methods. We are at the end of an era of relatively open data access, in the "post-API age" [@freelon_computational_2018]. Twitter, once the "model organism" of social media research [@tufekci_big_2014], has closed off academic access, and even access to the Reddit API has come into question. It is not clear where future data to study virtual social interactions will come from. At the same time, natural language processing methods have advanced significantly in the past few years, well beyond the simple word embeddings I used in this work to more complex large language models (LLMs), such as the series of GPT models and their competitors. LLMs are too data- and computation-intensive to train locally on niche data sources like queer Usenet groups, but will no doubt find other uses in academic research. In all, there are now greater limits to what an independent graduate student can do on their own. This is a loss because it is hard to imagine large research groups, much less private organizations, paying much attention to queer lives and experiences.

Outside of research, what kind of world makes for strong LGBTQ communities? This dissertation shows that experiences of community are not divorced from material reality. In terms of place-based community, availability of housing, transit, and public spaces would allow people to make the choice to come together. Without attention to queer spaces and queer visibility specifically in the realm of policy and planning, I would be concerned about a widening bifurcation in access among LGBTQ people. For creating a sense of community virtually, "augmented reality" -- an overlay of digital and offline lives [@jurgenson_digital_2011; @orne_boystown_2017] -- seems the most promising way forward. Soc.motss had its meetups, and I suspect the most cohesive subreddits do the same. Again, without deliberate thought, digital spaces too can be hostile or unwelcoming for LGBTQ people. Rather than a world of diverging or shrinking access to collective queer life, LGBTQ community can and should be available to everyone who wants it.

This work was meant to be something of a love letter to queer spaces. They can feel precarious and fragile; that they can exist at all can feel like a small miracle. In the present work, I have shown the conditions under which LGBTQ communities continue to thrive now, but I cannot predict their future. Over the course of the years I have spent on this dissertation, there has been a marked shift from increasing formal legal equality nationwide for LGBTQ people in the United States to growing backlash in the form of state-level legislation -- especially, in this moment, backlash against transgender people and against any forms of gendered existence and gender expression that challenge norms. Living queer lives, in public, is an expression of community. While LGBTQ people may be somewhat ambivalent about the continued salience of distinctive queer spaces, we are not that divided on the issue. On the whole, participating in queer community makes us feel more connected. May it continue to be so.
