---
title: Geography, Gemeinschaft, Identity
subtitle: Disentangling the meanings of "community" through word embeddings
---

## Introduction

When LGBTQ people talk about community, does what they mean invoke a _gemeinschaftliche_, belonging- and social organization-oriented sense of the concept? Do they invoke _Gemeinschaft_ to a greater extent than in more general and generic contexts? In answering these questions, this chapter responds, in part, to a call from @levine_paradox_2017 to investigate the power and ambiguity of "community" in contexts other than his own, where he shows how it operates as a rationale in the case of local governance; it also responds to a host of LGBTQ research that sometimes problematizes community [@orne_boystown_2017; @winer_solidarity_2020] and sometimes takes it for granted [@frost_measuring_2012]. I demonstrate how the empirical everyday meaning of "community" in an LGBTQ social context invokes sociological understandings of _Gemeinschaft_, of community as a meso-level form of social organization [@tonnies_community_2001; @brint_gemeinschaft_2001] -- albeit not exclusively. This evident salience of Gemeinschaft matters given the prevailing view of modern, urban society as instead promoting individualism and isolation
[@simmel_metropolis_1971; @putnam_bowling_2001], and how those individualistic trends have been intertwined with the historical development of LGBTQ identities [@demilio_capitalism_1992].

To approach the question of how salient community as Gemeinschaft is for LGBTQ people, I examine how the concept of "community" shows up in one LGBTQ-centered social group. Founded in 1983, a Usenet group called soc.motss ("soc" meaning one of the many groups for social discussion, and motss standing for "members of the same sex") is the earliest known virtual community built around a shared LGBTQ identity [@auerbach_first_2014]. This makes it unique and important, because it sets a precedent and influences how later online groups become ubiquitous fora for discussing community, identity, and many other topics [@dym_coming_2019]. The data I use from soc.motss are an archived corpus of individual messages sent to the group from the late 1990s through the 2000s. For a comparative baseline, I draw on a large volume of Internet text, not directly, but mediated through an off-the-shelf natural language processing (NLP) model. This baseline represents general or generic contemporary English-language discourse.

TODO: why virtual? => reasons Kate says [what were those reasons?]

This chapter adopts innovative NLP methods to learn about community from how the word is used in naturally-occurring language. I systematically investigate the connotations of community across text using word embeddings [@mikolov_efficient_2013] -- a type of model that mathematically represents words based on the contexts in which they appear. Word embeddings are well-suited for investigating the semantic dimensions of social concepts and how they vary across contexts because -- unlike other methods for computational text analysis -- they move from surface-level words to underlying meanings and their relations [@stoltz_cultural_2021; @arseniev-koehler_machine_2022]. By first engaging in a close read of how "community" is represented in a general word embeddings model pretrained on large amounts of online text (approximating a generic social context), I lay the foundation for interrogating how the meaning of "community" in the context of soc.motss differs from that generic context, and how it remains similar. Specifically, I use dimensionality reduction and algebraic transformations to assess how related "community" is to three latent semantic dimensions -- geography, Gemeinschaft, identity -- in each of those contexts.

I hypothesize that, in a self-selected virtual community based on LGBTQ identity, if community itself is salient as a topic, then members will visibly talk about community as Gemeinschaft. If, by contrast, community is backgrounded and ambient, other senses of the word will be more evident in the localized embedding of the term. What I find is that the discourse in the soc.motss LGBTQ Usenet group uses community in the sense of Gemeinschaft to at least an equal extent compared with general English-language text. The key semantic difference is that it also deemphasizes the geographic aspects of community and replaces that with connotations specific to LGBTQ identities. In other words, I show that "community" in the general sense brings together two semantic domains -- geography and Gemeinschaft; in a queer context the geographic connotation recedes to the background and a third domain, identity, emerges to take precedence. Community in the sense of Gemeinschaft turns out to be the common bridge between the general and LGBTQ-specific contexts.

## Background

I can keep a lot of the background because why the fuck not. the main section that needs elaboration is the one about the context of Usenet, which I've started to jot down.

### "Community" and the meanings of concepts

Community has a power and ambiguity that render it suitable for strategic rhetorical uses in everyday discourse. Two qualitative examples illustrate the shades of meaning that "community" can take on; together, these illustrate the range of variation that I might expect to see in a computational investigation of what community means as a folk concept. First, in the context of local governance, @levine_paradox_2017 observes that "community" becomes a "floating signifier of the good," a halo of positivity to cover the real operation of local decision-making and to provide legitimacy for action. For Levine, this is harmful; he notes the impossibility of "the community" wanting one single thing as a uniform entity, and the harms of ascribing collective representational authority to whoever can show up to participatory events [@levine_constructing_2021]. In his case, the word is constantly used in a positive and justificatory light, but so flexibly as to lose coherent meaning. Second, and in contrast to that wholehearted positivity, @winer_solidarity_2020 finds that his interviewees have an ambivalent and distancing relationship with the "imagined gay community," drawing a distinction between "the community" at large and their own social circles. Rather than pure vagueness, this points to another specific rhetorical use, to critique an in-group's flaws rather than to justify desired actions. In these accounts, "community" assumes differing valences, with slippery or counterintuitive referents, but in each case the concept does important discursive work. I do not aim to create a taxonomy of these rhetorical strategies; instead I'll show how all of these uses together add up and contribute to the overall semantic resonance that "community" takes on. Language, after all, is social and shared [@saussure_cours_1972]; later I'll show how that shared foundation can be a springboard for understanding local deviations.

For fully understanding the social life of a complex concept, academic definitions are insufficient on their own, but worth reviewing as an anchor for comparison. "Community" is a phenomenon sociologists have elaborated on since @tonnies_community_2001; they've created taxonomies of different types of communities [@brint_gemeinschaft_2001]; argued over what communities count as "real" [@driskell_are_2002; @rheingold_virtual_2000]; and debated about what features -- shared social networks/interactions or shared cultural/moral traits -- are most fundamental to the creation and experience of it [@vaisey_structure_2007; @boessen_networks_2014]. What emerges consistently is the metaphor of a tightly knit social fabric, a group of people bound together by shared ties, shared culture, and possibly shared place. 

However, the issue with using academic definitions of "community" as a starting point is that a strict definitional logic of concepts and categories does not apply "out there" in the real social world; classical logic may be useful for technical jargon, but it is not how ordinary human concepts work. Instead, everyday concepts are fuzzy and prototype-based [@rosch_family_1975; @lakoff_women_2008; @lakoff_women_2008; @bowker_sorting_2000; @zerubavel_fine_2002; @monk_inequality_2022]. One way to see this is to think about how people figure out that something _is_ a community in the first place. As @bruckman_should_2022 argues, we might decide that a virtual community like Wikipedia is a community through mental comparison to prototypes of community like a small town. A given example of community does not have to have all of a specific set of features in order to fall under the concept; rather, concepts and categories are bundles of "intensions," inherently fuzzy constellations of characteristics and cues. "Community," as an everyday concept, bundles together a spread of connotations; as I will show, the most notable of these are a geographic sense of "local place" and a sociological sense of "social group" or "object of belonging." Because "community" encompasses both, even the most mundane use of community to refer to local place might still invoke the sentiment and connotation of *Gemeinschaft*. That is partly where the fuzziness and ambiguity of community as a concept could come from, and also part of the concept's discursive power. However, distinguishing these two senses is necessary in order to open up a window into where and how the underlying meaning of *Gemeinschaft* and belonging appears in different discursive contexts.

Alongside these two senses of geography and Gemeinschaft, I examine the potential overlap between community and identity. In general, shared social identity characteristics are one potential basis for communities [@brint_gemeinschaft_2001].At the same time, in the context of the cultural sociology of markedness, @zerubavel_taken_2018 notes that this basis is not necessarily available for unmarked identity categories: "the heterosexual community" is an empty, nonsensical statement, while "the LGBTQ community" is a common and sensical one. The open question, however, is about how community and identity are link when a virtual community like soc.motss is already centered around LGBTQ identities. Given the shared context, there is the possibility that those identities will be backgrounded rather than foregrounded in the context of discourse about community.

### Using word embeddings to measure meaning

This project, then, uses an empirical, inductive, and computational approach to discover what community means and compare it to theoretical expectations derived from sociological literature. It integrates the sociological definition of Gemeinschaft in an iterative way, making this an abductive approach [@brandt_abductive_2021], rather than a purely grounded one [@nelson_computational_2017]. To examine the resonances and connotations of community in generic English discourse, word embeddings are my computational method of choice. Word embeddings are a relatively recent [@mikolov_efficient_2013] computational operationalization of an old linguistic idea, called the _distributional hypothesis_ [@sahlgren_distributional_2008]. As @firth_synopsis_1957 put it, "You shall know a word by the company it keeps." Accordingly, these models represent words as a function of all of their immediate contexts. To give one example: 

> "The history of all hitherto existing **society** is the history of class struggles." [@marx_communist_1972]

An embeddings model would take this sentence and learn about the semantic connotations of the the word "society" from its position near "history", "class", and "struggle"; it might also learn linguistic features common to nouns from its position in relation to words like "is" and "of." Naturally, a model needs many such examples as training data, to produce a single overarching numeric representation for each word in a vocabulary.

There are two main commonly-used word embeddings models -- word2vec, based on a shallow neural network [@mikolov_efficient_2013], and GloVe, based on cooccurrence matrix factorization [@pennington2014glove]. These approaches are mathematically related to each other and the substantive differences in the resultant embeddings are minor, and so I choose one or the other for practical reasons of convenience and convention [following e.g., @rodriguez_word_2020 and @nelson_leveraging_2021]. Specifically, high-quality and widely-used pretrained models have been released based on the GloVe method [@pennington2014glove], while a high-quality and robustly-engineered Python software package, gensim, implements the word2vec method for training new models on particular corpora [@rehurek_lrec]. These basic word embeddings approaches are foundational for a host of subsequently developed NLP methods, from contextual word embeddings models like BERT [@devlin_bert_2019] all the way to large language models like the GPT family of generative models [@brown_language_2020]. The simpler word embedding models offer the most straightforward and interpretable entry point for addressing the question of what "community" means in everyday English-language contexts.

A generic model with a robust, comprehensive view of as many contexts as possible would approximate "the" meaning of every word in a language. To train general models for a given language, the most common corpora are large and publicly accessible texts from the Internet, e.g., Wikipedia pages, newswire articles, social media, or anything else that can be conveniently crawled from the web. (Historical embeddings use digitized book corpora.) These pretrained models can be used for a variety of questions and tasks, but they stand in contrast to locally trained models derived from specific corpora. Of course, meanings of words do vary -- over time, over space, and by other social characteristics [@bamman_distributed_2014; @soni_abolitionist_2021]. A general model trained on easily-accessible data works to the extent that meanings are common or shared; of course, this flattens variation. Given the social characteristics of the authors of formal online texts like Wikipedia or news corpora, in terms of gender, race, education, nationality, etc. [@hargittai_mind_2015; @vrana_16_2020], models trained on those data necessarily overrepresent hegemonic cultural viewpoints. This overrepresentation is a form of bias, but also a matter of substantive interest [@caliskan_semantics_2017; @garg_word_2017; @jones_stereotypical_2020]. 

Distinct from other text-as-data methods (e.g. keyword dictionaries or topic models), embeddings models create dense, distributed vector representations of words. In this way, word embeddings encode a relational model of meaning; they build up a system of signs [@saussure_cours_1972], a vocabulary, in which distances (or their inverse, _similarity_ measures) in a high-dimensional space can be calculated between every pair of words. This makes embeddings useful for social-science problems where meaning matters -- especially where variations or changes in meaning are of interest. For instance, they have been applied fruitfully in cultural sociology to show how the distinct dimensions of class correlate and evolve over the course of the 20th century [@kozlowski_geometry_2019], and in political science for modeling ideology in parliamentary debates [@rheault_word_2020]. An embeddings model can be thought of as distilling shared, declarative public culture [@lizardo_improving_2017]; @arseniev-koehler_machine_2022 go even further to argue that the training process is a reasonable heuristic model for actual cultural cognition.

But the dimensions the models learn are not themselves interpretable (nor are they consistent across models, meaning that different embedding matrices must be aligned for comparison). To derive interpretable dimensions, social scientists use anchor words and simple algebra. One common approach is to construct new binary dimensions through subtraction [@kozlowski_geometry_2019; @taylor_integrating_2020], opposing pairs of concepts that can be thought of as antonyms (e.g. rich - poor, woman - man). This idea springs from the algebraic analogy tasks that first made word embeddings notable in NLP (e.g., king - man + woman $\approx$ queen). While these binary oppositions have a clear basis in cultural sociology [@durkheim_elementary_2001; @saussure_cours_1972; @douglas_purity_1966], they are not the only possibility. They do not necessarily make sense for a concept that might bundle together multiple overlapping connotations or characteristics.

Instead, in this work, I deviate and borrow a different algebraic idea from NLP: "de-biasing" an embedding through orthogonal projection away from a target word vector [@gonen_lipstick_2019]. This approach originates in an attempt to mitigate gender bias in the words for different professions and occupations -- which is undesirable for NLP tasks such as machine translation [@caliskan_semantics_2017], even if it represents cultural associations or demographic facts about particular occupations that might be worth studying in themselves [@jones_stereotypical_2020]. That foundational work on this method makes it clear that it does not remove all the connotations of the undesired word -- i.e., it does not fully succeed in de-biasing -- but it is successful enough to use to disentangle the connotations of a concept like community. I can then compare how those connotations vary between a general context and the specifical local context of soc.motss.

### An early LGBTQ virtual community: the soc.motss Usenet newsgroup

My case study is an early virtual community, an LGBTQ Usenet group called soc.motss. The soc.motss archive spans a key time period when the position of LGBTQ people in American society is shifting towards greater acceptance and equality, centered on the late 1990s and early 2000s (see @fig-posts below). It captures LGBTQ discourse on the heels of the Don't Ask, Don't Tell military policy (1993) the Defense of Marriage Act (1996), at the early end of a two-decade-long shift in public opinion in favor of LGBTQ equality [@rosenfeld_moving_2017]. Simultaneously, the legal landscape starts to change, from _Lawrence v. Texas_ decriminalizing same-sex sexual relations in 2003 to _Obergefell v. Hodges_ legalizing same-sex marriage in 2015.

Usenet is a distributed system for sharing electronic messages which predates the contemporary Internet [@rheingold_virtual_2000], organized into topical groups such as alt.atheism or rec.motorcycles (to take two examples from the "20 Newsgroups" dataset [@Lang95]). Some of these groups are reported to have had a strong sense of community, while others were known for their hostility [@baym_practice_1994; @dame-griff_herding_2019]. Usenet is of interest because the moment of its heyday is when people were demonstrating that virtual community was, in fact, possible [@driskell_are_2002; @rheingold_virtual_2000; @hampton_neighboring_2003; @calhoun_community_1998]. Moreover, as @boyd_its_2014 points out, even if particular platforms are passé, the social processes that unfold on them are not. Usenet groups are well-suited for studying the creation of community using computational text analysis methods because they are both conversation-oriented and text-based [@mcculloch_because_2019]; these kinds of virtual interactions can have similar feedback effects to those associated with face-to-face interaction rituals [@dimaggio_interaction_2018].

Usenet preceded the period when the majority of people in the United States used social media, and is instead from a time period when virtual spaces provided an outlet for outsiderness [@boyd_its_2014]. Soc.motss members are a self-selected group, both in their avant-garde usage of technology and in their desire to seek out LGBTQ community spaces. They are described as more introverted on the whole, and so these individuals might not have had as much access to or comfort in in-person LGBTQ spaces like gay bars [@auerbach_first_2014]. As were other virtual communities of the time [@rheingold_virtual_2000], they are likely disproportionately concentrated in tech centers and centers of gay culture like the Bay Area. Despite that geographic distribution, however, soc.motss affords the opportunity to use digital technology to find LGBTQ community in a way that potentially transcends geography.

Because of stigma and isolation, LGBTQ people may be especially predisposed to seek out queer community in digital spaces. The internet has long been recognized for its potential for marginalized groups, given the possibility of anonymity and the ability to manage contexts to control the disclosure of identities in unwanted ways [@mehra_internet_2004; @boyd_what_2015]. As such, LGBTQ people can use virtual communities for connection and support that may be lacking in offline social spaces [@dym_coming_2019]. Corroborating this potential, LGBTQ groups and interests have been present and visible since the earliest virtual spaces came into being[@rheingold_virtual_2000; @auerbach_first_2014]. The continued utility of technology for LGBTQ community-building is evident in the way that LGBTQ people have continued to act as early adopters of new technologies for digital social life (e.g., mobile and location-based platforms [@orne_boystown_2017]) through to the present day.

Soc.motss -- where "motss" stands for "members of the same sex" -- was oldest and largest LGBTQ Usenet group. According to a history recounted by @auerbach_first_2014 in *Slate*, it was founded in 1983 (as net.motss), not long after Usenet came into existence in 1980. In terms of case selection, soc.motss is worth studying not because it is typical or representative, but because it is unique and historically important. As "the first gay space on the Internet" [@auerbach_first_2014], it influenced the many queer spaces that would come after it; as one of the largest spaces of its time period, it provides a sufficient corpus for modeling with word embeddings.

An [archived version](https://web.archive.org/web/20010629135057/http://www.soc-motss.org/doc/faq/faq_participants.html) of the soc.motss FAQ from 2001 describes the group as follows (in a section headed 'Our "we"'):

> Soc.motss serves non-heterosexual Internet communities. To signal inclusiveness, we use the acronym LGBTO, for Lesbian, Gay, Bisexual, Transgendered and Others, "others" meaning supportive straight people. The newsgroup is a predominantly non-heterocentric space where we can discuss issues of importance to our communities.

Elsewhere, the FAQ provides ample evidence that this *is* a cohesive group and a virtual community by any definition of the term. It has norms for participation, a group discursive style [@eliasoph_culture_2003], and community-building events like in-person meetups ("motss.con") [@auerbach_first_2014; @rheingold_virtual_2000]. Of course, there were other LGBTQ newsgroups as well, such as soc.support.youth.gay-lesbian-bi or the several trans Usenet groups @dame-griff_herding_2019 has already studied. Few of these are large enough to support training distinct models, and it would muddle the analysis to combine many potentially distinct group cultures and discursive styles together in one corpus. On its own, soc.motss offers a well-defined, prototypical early LGBTQ virtual space, in which to investigate how LGBTQ people construct the meaning of community together.

## Data and methods

some confusing bits here apparently. I think I just need to answer kate's questions and move on.



## Results

defend my fucking choices because they are good choices and I'm not changing them. most work to do here I suspect





## Discussion

Kate liked this part for the most part.

