# Introduction

## Short version

### Questions and goals

In this dissertation, I propose to study expressions of and experiences of community in order to better understand what community means, how community happens, and what community does. My empirical focus is on expressions of community from LGBTQ people, because community in LGBTQ contexts is highly resonant and visible rather than relegated to the background or taken for granted.

My investigation will proceed in three parts. I begin by examining **how the ordinary meaning of community is constructed through its use.** Does everyday talk about community invoke or map onto sociological understandings of *Gemeinschaft*? Are those sociological resonances more apparent in LGBTQ community discourse than in more generic or neutral social contexts? Second, I'll investigate **how individual sense of community varies across place-based contexts.** Do simple structural features of place-based contexts suffice to explain variations in belonging? Or are there differences beyond that, something more? Third, I'll investigate **the consequences of community-oriented talk in virtual communities.** Do linguistic expressions of community come from embedded or peripheral actors? Do they result in downstream interactional consequences, or are they mere rhetoric? 

This work will make two contributions: First, I aim to refine our understanding of how distinct aspects of community -- shared culture, place, social ties -- relate to each other; I anticipate finding that these are largely complementary rather than substitutes. Second, I aim to connect some disparate threads across existing research in order to systematically show that community can happen in at least two distinct ways: either it can be predicated on sameness in a narrow and exclusionary way, or it can be intrinsically heterogeneous and inclusive. The former is unsurprising, but the latter type of community expands the boundaries of how we might think of community as being empirically possible.

Recent historical and contemporary LGBTQ communities provide an interesting set of cases for me to draw on in order to understand the operation of community writ large, for several reasons. First, LGBTQ community cannot be taken for granted; LGBTQ people who want community together must actively seek it out (sometimes through literal migration) and build it. "Queer cultural reproduction" [@orne_boystown_2017] takes conscious choice and effort. Compared to contexts where community might be relegated to the background, like Tönnies's stereotypical peasant village, this makes LGBTQ expressions of community highly visible and conducive to study. Second, even though the historical emergence of LGBTQ communities and identities is a relatively recent phenomenon [@berube_my_2011; @demilio_capitalism_1992], LGBTQ communities cover the full range of things that a community can be, according to typologies of Gemeinschaft like @brint_gemeinschaft_2001's. Such communities can be virtual or emplaced; they can span from concrete social ties to imagined collectivities. Metaphorical concepts like constellations [@gieseking_mapping_2020] and archipelagoes [@ghaziani_there_2014] are used to characterize and emphasize the variety and interconnectedness of queer communities (for those two authors, specifically as they unfold in urban spaces). This variation is real and meaningful but not infinite; @winer_solidarity_2020 has shown how "gay imagined communities" possess a clear, concrete "imagined center" to which individual gay, bi, and queer men have ambivalent relations -- what Winer calls "solidarity with disdain."

Finally, LGBTQ communities can be homogeneous or diverse. Sometimes differences and tensions divide lesbian, bi and queer women from gay, bi and queer men; lesbians and gay men from bisexuals; cis LGBQ people from trans people; and queer people from people with more defined or less fluid orientations. Sometimes, LGBTQ people bridge those differences and build community together. They also can bridge or fail to bridge other kinds of social difference: race, age, class, and so on. A rich qualitative literature documents and categorizes the forms LGBTQ community can take, establishing that multiple distinct types of LGBTQ community can exist, characterized in part by their differing approaches to difference. @brown-saracino_how_2017 shows how, for LBQ women in small cities, there might be a singular "lesbian community" premised on the sameness of identity, or a "hybrid" form of identity and community predicated on identities that are diverse and plural instead -- or else, a third option, LBQ community can be effectively nonexistent, folding into a broader "ambient community" instead. @orne_boystown_2017 charts the "Disneyfication" of Boystown in Chicago alongside the failures of alternative queer political spaces to live up to their ideals; instead, they find the most radical and interesting potential in "sexy communities." Together, these two ethnographies show that both ways of forming community around a shared identity -- shared sameness, or shared difference -- happen in various times and places. I'll develop a way of studying expressions of community that accommodates both of these possibilities, and I'll foreground heterogeneity when I turn to studying perceived experiences of community.

### A few theoretical clarifications

It's worth emphasizing at the outset that identity does not automatically create community. A conceit of this project is that identities like sexuality _might be_ a basis for creating community, but probably only in conjunction with other features that might be shared, and active work on the part of cultural entrepreneurs. It is because community building in this context takes work that the study of expressions is so valuable.

What are those shared features that might make up a sociological definition of community? My work focuses on three: shared culture, shared ties, and shared place. I think it's possible to rank those features, in that order, based on prior research that's gone into refining the concept of community and exploring its limits. I don't plan to reevaluate the relative importance of these factors in this dissertation, but the structure-culture tension and the disputed role of place affect the operational choices I make and will shape how I interpret my findings.

Why culture over ties? The starkest example is the concept of "imagined communities," which dispense with the possibility of interaction among all, or even most, members of a given community entirely. Beyond that, however, a number of studies have found that a shared moral order [@vaisey_structure_2007] or perception of cohesion [@boessen_networks_2014] matters more for creating a sense of community (Gemeinschaft) than do social interactions or ties. 

Why ties over place? If community has turned out to be "liberated" rather than "lost" [@wellman_community_1979; @kelly_exploring_2014], and if virtual community is possible [@driskell_are_2002; @rheingold_virtual_2000], then that suggests that shared ties take precedence over shared place. But at the same time, these characteristics might complement rather than supplement each other. We know that the rise of virtual connections has not led to the death of distance [@spiro_persistence_2016], and mostly-virtual communities can hold in-person meetups that strengthen members' sense of togetherness [@rheingold_virtual_2000]. (More generally, "augmented reality" rather than "digital dualism" describes how virtual and offline experiences of community might intersect [@jurgenson_digital_2011; @orne_boystown_2017].)

Given this complementarity, another way to put this might be that the more of these features are present to some degree, the more "prototypical" a community looks [@bruckman_should_2022]: a tight-knit small town has all three, a group of Wikipedians has two, and a nation-state has only one. But breaking down the potential features that create a community goes some way toward explaining a key finding from qualitative studies of everyday conceptualizations of community [@levine_paradox_2017; @winer_solidarity_2020], that the _referent_ for "community" can be hard to pin down precisely. Is it all the people in a place, a set of people with social relations to each other, or people connected by a shared (sub)culture? This referential ambiguity partly arises from the multiple, potentially conflicting, elements of the definition of community.

But, backing up one step further, there's one more theoretical point to clarify: what's culture, anyway? At least as it relates to creating community, culture extends beyond moral values and beliefs, to include group styles, norms, and practices; it includes both declarative (i.e. linguistic or discursive) and nondeclarative (i.e. practical or embodied) modes [@lizardo_improving_2017]. Reproduction of queer cultures -- and thereby queer communities -- manifests everywhere from socialization into particular kinds of lesbian identity talk [@brown-saracino_how_2017] to acquisition of a particular gay habitus [@orne_boystown_2017]. I'd use those examples to deviate from @vaisey_structure_2007 and argue that in focusing only on moral values as key to Gemeinschaft, he's not expansive enough. 

But what does it mean for culture to be shared? And why do I think something like "cultural density" might be better than "moral unity" [@vaisey_structure_2007] to describe how shared culture generates community? Culture is structured; beliefs, values, symbols, etc. fit together into systems of meaning through schemas and frames. Without delving too deeply into the cognitive details, I think certain configurations of cultural ideas and practices allow for the incorporation of diversity and variation into the framework of a single community, while others don't; again, I lean on those examples from Orne and Brown-Saracino as a sort of existence proof.

### A note on methods

I am taking a quantitative and computational approach to studying LGBTQ expressions of community. This offers a breadth and scale that complements and extends the deeply grounded research that already exists in this area. It's also a logical fit: given my theoretical framework and expectations, I need a window into how culture is structured, and I need to connect other attributes like ties, interactions, and place. Computational and digital methods -- especially techniques from computational text analysis -- provide this. They expand what can be done with traditional quantitative methods and enable me to build more directly on prior qualitative research. CSS methods can incorporate more insights from qualitative work into a quantitative framework, especially in terms of measuring and operationalizing culture [@mohr_measuring_2020]. Novel techniques like word embeddings are particularly suited for measuring how culture is structured into schemas and frames [@boutyline_all_2021; @arseniev-koehler_machine_2022]. These methods have limitations; most explicitly, they are not suited for studying the nondeclarative, embodied aspects of group culture [@lizardo_improving_2017; @orne_boystown_2017]. That is one reason for my focus on the linguistic, discursive aspects of culture and community. There will be other gaps -- wouldn't it be ideal if I had the kinds of data I plan to use in chapters 1, 2, and 3 all for the _same_ LGBTQ community or set of communities? -- but triangulating through multiple, partial cases is the most realistic way forward.

## Long version

### Introduction

"Community" does a lot of work out there in the social world. Why do social media companies purport to give people tools to "build community" with -- and why have billions of people adopted those tools? Why do protestors demand not only that cities defund police departments, but also that they "invest in community" instead? In these varied circumstances, community is a motivation, an end, an object of desire, even an solution to social problems. I'll pose community as a question instead. I want to investigate variations in what community means, how it happens, and what it does, by focusing particularly on the varied experiences of LGBTQ people and the communities they belong to. 

At the same time, significant debates about the nature and operation of community have long taken place in sociology. What's the relation between community and society [@tonnies_community_2001]? Has community been lost or saved or liberated in contemporary post-industrial societies [@wellman_community_1979; @wellman_networks_1979; @kelly_exploring_2014; @hampton_lost_2018]? How bound is community to place, or is virtual community also possible [@driskell_are_2002; @rheingold_virtual_2000; @calhoun_community_1998; @baym_practice_1994]? Though many of these debates are settled, they show that community is an object of theoretical contention as well. I aim to unsettle some of what we think we know about community, by paying close attention to the margins of the phenomenon.

I'll do this through triangulation, attacking the phenomenon from multiple complementary angles. As you read this proposal, you might see ways any one chapter could be expanded into a deeper, more focused dissertation on its own. But I'm aiming for breadth instead. In other words, I plan to shamelessly take advantage of my disciplinary home in sociology -- not linguistics, not geography, not human-computer interaction. I'm not bound to study language, or place, or technology -- only some facet of the social world. I can follow a social phenomenon, and a group of people for whom that phenomenon is often important, across multiple contexts. Those are my anchors.

Right now, each chapter proposal stands somewhat on its own. As they develop, I'll work to bring them closer together. I'd appreciate any thoughts you have about how to shape these projects so that they bend toward each other and align into a coherent whole. At the same time, by having distinct focal points, the chapters offer ways to bracket some of the moving parts -- chapter 1 focuses squarely on discourse but remains somewhat descriptive; chapter 2 brings in representative survey measures but sacrifices some richness and detail; chapter 3 gives up that representativeness in order to study relational processes in more depth.

<!-- [The meta-question goes here]  -->

At a discursive level, I will examine the literal meaning and broader resonance of "community," as part of a relational system of words and meanings. How does community vary in terms of what it means in everyday social discourse? How do expressions of community vary among social groups and social contexts? Can linguistic expressions of community and belonging be a measurement tool for something deeper? In LGBTQ contexts I expect the meaning of community to be more closely tied to identity and to Gemeinschaft than to mundane notions of place; I also expect more frequent expressions of language invoking community and belonging. 

<!-- [This is descriptive; this will establish something weird is going on here.] -->

Scaling up to the level of broader contextual characteristics and down to the level of individually-reported experienced sense of community, I will next investigate the relation between the two. How do cultural and place-based features like density and diversity shape variation in individual sense of community? I expect those features to facilitate community and belonging for LGBTQ people, especially in their connectedness to the LGBTQ community specifically, where they might not do the same for other groups of people.

Finally, at a relational level, through a case based in virtual communities; connect discursive measures from the first project with similar contextual features as in the second. How do expressions of community relate to structural and interactional dynamics like embeddedness within a group? While I expect the most embedded individuals to strongly invoke language of community and belonging in order to build community for the group, the most peripheral individuals within a network may do likewise in their own attempts to belong. LGBTQ virtual spaces provide a context wherein expressions of community are highly visible and where these processes can be observed.

This multifaceted, multi-pronged investigation matters because it interrogates who community is for and when community is possible. What are the limits, the edges, the boundaries? Who gets to experience belonging? Some framings of community are conducive to diversity, heterogeneity, and inclusion; some are narrow, homogenizing, and exclusionary. The former offer more chances to more people to have experiences of community. To the extent that community is a positive thing for individuals to experience and participate in, something worth creating and seeking out, finding out more about the unexpected and counterintuitive conditions under which belonging can emerge is a worthwhile endeavor.[^bad] Moreover, in addition to being an end in itself, community can be a precursor to various forms of collective and social action, like political mobilization. Understanding variations in the meaning, the conditions, and the consequences of community enriches our knowledge of a phenomenon that provides grounds for much of social life.

<!-- [this could be an inequality story, I guess] -->

<!-- Footnote: In addition to the general why, there's a personal why as well; this theme, this topic, didn't materialize out of thin air. For some people, a desire for community and belonging is a significant motivation for their actions, both day-to-day and in the overall arcs of their lives. I'm one of those people. -->

[^bad]: Community is bad sometimes -- i.e., even when an individual experiences it as a positive, the externalities of it can be quite negative. Think of white nationalist groups or men's rights activists or QAnon conspiracy theorists. One of the things people in those groups talk about gaining is a sense of belonging; many outsiders might seriously prefer that these people found some other way to achieve that experience. Granted, other people think that queer community is literally destroying the fabric of society.

### Motivation

#### Background

Community is a meso-level social phenomenon that springs into existence when certain conditions are met. In turn, it's something people might long for or become attached to, something that can motivate them to individual or collective action. There's a stable core to this phenomenon which is well understood, because community has long been one of the core sociological concepts. Community is the product of social density and cultural density, the result of both of which is the perception and reality of a group people can belong to and form attachments to. Social density in the form of relations and interactions is essential, but network cohesion alone is not sufficient for the emergence of a coherent and perceived community. Social density is often associated with physical density or emplaced co-presence [@durkheim_division_1997; @collins_interaction_2004], but the reality of virtual communities has shown that place, while beneficial, is not essential to the formation of community [@rheingold_virtual_2000; @hampton_neighboring_2003]. What is necessary, however, is some form of shared culture. The precise terminology for cultural density varies in the literature; for instance, @vaisey_structure_2007 refers to "moral unity" as the key to _Gemeinschaft_, while @tavory_summoned_2016 refers to "moral density"; I prefer "cultural" over "moral" because it encompasses norms, styles, and schemas that aren't necessarily moral values, but am alluding to the same domain. Similarly, I use "density" over "unity" because the latter takes for granted an assumption of sameness or uniformity, which is not universally present in all communities.

Despite these recognizable core characteristics, community is also a notoriously broad and ambiguous concept. Partly this is because communities come in a complex taxonomy [@brint_gemeinschaft_2001], from the prototypical peasant village [@tonnies_community_2001; @bruckman_should_2022] all the way to virtual [@rheingold_virtual_2000] and imagined communities [@anderson_imagined_2016]. At the margins are types of communities that call key facets of the concept into question. For instance, virtual communities are noteworthy because they unsettle the centrality of place, showing that togetherness in place isn't essential to creating a community -- even if the theory of augmented reality (as opposed to digital dualism) shows that place can still play a role even for virtual communities [@rheingold_virtual_2000; @jurgenson_digital_2011; @orne_boystown_2017]. Imagined communities, similarly, challenge the centrality of social interaction (but "are imagined communities real?" is an oxymoron). While this extensibility might seem to render the notion of community so flexible as to be analytically useless, individuals prove to be quite capable of perceiving community in the social world. A useful way to account for this flexibility is to conceive of community as a fuzzy, prototype-based category [@lakoff_metaphors_2008; @lakoff_women_2008; @bowker_sorting_2000; @bruckman_should_2022]. Layering more of these features -- shared culture, social ties, togetherness in place -- together produces more recognizable, more prototypical instances of community.

One way to observe how and where the meso, group-level phenomenon of community happens is at the individual level. This measurable individual experience and feeling of belonging is called "sense of community" [@mcmillan_sense_1986; @mcmillan_sense_1996; @mannarini_multiple_2009; @frost_measuring_2012; @boessen_networks_2014], and it generally implies the perception that a group exists and that the individual is a member. This could be a misperception -- all of the typical caveats of self-reports apply! -- but I find that generally unlikely. Individual sense of community is a useful barometer for the actual reality of community for two reasons.First, the threshold for forming an actual group is low (according to @simmel_dyad_2012, three people). Second, even if something perceived as a community completely lacks something sociologists might consider a fundamental definitional characteristic, that perception is informative -- and that affective, experiential dimension really can shape individuals' social actions. This is, in fact, the insight behind imagined communities; though they operate at a scale where social interaction is impossible, they are real enough to motivate people to acts they would not engage in otherwise [@anderson_imagined_2016]. Sense of community is a psychological rather than sociological concept, in individuals' heads rather than out there in the world. But some social phenomena are perceptual, cultural, and distributed, even shared collective feelings or experiences; community is one of those phenomena. Accordingly, measures of sense of community are one angle I'll take to understand how community itself happens.

While _community_ and _sense of community_ are well-established concepts and measures, I would propose a third, called _expressions of community_. This is a language or vocabulary of belonging, encompassing both explicit invocations of the concept of community as well as implicit statements that resonate with it. With this concept, I deviate from studies that measure belonging through subcultural innovation and group conformity [e.g., @lucy_characterizing_2021]. Adoption of a group discursive style is one way a group culture is produced [@eliasoph_culture_2003], of course, but not the same thing as expressions of community. Expressions of community are relational and potentially performative, i.e., they might be part of the process of creating community for a speaker or an audience. This potential is most evident in social discourse that is interactional, like a conversation. For instance, suppose that two members of a group chat are debating the efficacy of vaccines, in an increasingly contentious way. A third member steps in to intervene, stating that we, as a community, have a range of opinions on many things, but we all belong together. Both contending parties moderate their debate going forward. Invoking community here is an act of repair, and achieves its intended proximate effect of reducing conflict -- but for all parties involved, and for any bystanders, it potentially strengthens the very community being invoked. These attempts to invoke community are maybe not always successful in creating community. For instance, no matter that a property management company insists that its pricey apartment complex offers the chance to be part of a community alongside other amenities, this does not mean that neighbors actually talk to each other, much less feel any real sense of connection.[^washing] Observing the linguistic phenomenon and measuring its effects are distinct. Sociologists might interpret community talk as a kind of ritual [@durkheim_elementary_2001; @collins_interaction_2004], part of the work of welcoming new members, reaffirming longstanding commitments, or even repairing the group in moments of tensions. These expressions of community can be emotional, frequently bordering on trite and sentimental, but are still worth taking seriously for the impact they might have. In some circumstances, of course, they could be so formulaic and pervasive as to be bleached of meaning. In that way, part of what community talk simultaneously does is construct the meaning of community.

[^washing]: One way to describe unsuccessful attempts at invoking community that are particularly blatant, cynical, inauthentic, or exploitative is "community-washing", by analogy with similar terms. I'm not alone in coining this term, which I first used privately in October 2020; a pair of British researchers came up with it independently in March 2021. https://sifted.eu/articles/community-led-platforms/

#### Research questions

Expressions of community provide the first puzzle for this research. How do they construct the meaning of community, and what connotations does that meaning entail? How does the meaning of community vary across discursive social contexts, as well as the depth and resonance of invocations of belonging? If part of what makes "community" ambiguous and hard to pin down is that it's a folk concept as well as an academic one, then treating the meaning of community as an empirical question is one way to make progress. Seeing if that meaning *varies* systematically will also be revealing -- in my case, I suspect that community talk is ultimately more shallow in generic contexts and deeper and more resonant in texts coming from marginalized groups.

A second puzzle: how can "community" accommodate variation? Structural embeddedness and interactional density feel relatively clear to conceptualize and measure, though "ties" are cultural constructs [@white_notes_2008] and interactions presumably are as well. Cultural embeddedness, as @goldberg_fitting_2016 might call it, or cultural density, as I prefer, is not so clear-cut. Does cultural embeddedness mean conformity? If so, how might we make sense of community spaces or groups that contain riotous diversity, wide ranges of self-expression, and strong norms of inclusivity? I'd argue that there are communities that are "dense" along this cultural dimension without being uniform. Maybe one reason is that beliefs and values and other constituent elements of culture aren't a hodgepodge simply stacked atop each other, they fit together in schemas and people use agency in engaging with them as a toolkit [@hunzaker_mapping_2019; @swidler_culture_1986; @boutyline_improving_2017; @goldberg_mapping_2011]. One simple way to make progress here might be to return to individual-level sense of community, and see whether that can be high in contexts of structural and cultural variation. Another way might be to leverage the distinction I drew above between group style, which implies a something shared or the same among group members, and linguistic expressions of community, which might provide a window into how community might exist alongside difference. Metaphorically, poking at the edges of the concept of community is how I expect to uncover things that are interesting and unknown about how community happens and what it does in the world. 

#### Case

> Queer Counterpublics
>  
> By queer culture we mean a world-making project, where "world," like "public," differs from community or group because it necessarily includes more people than can be identified, more spaces than can be mapped beyond a few reference points, modes of feeling that can be learned rather than experienced as a birthright. The queer world is a space of entrances, exits, unsystematized lines of acquaintance, project horizons, typifying examples, alternate routes, blockages, incommensurate geographies. World making, as much in the mode of dirty talk as of print-mediated representation, is dispersed through incommensurate registers, by definition *unrealizable* as community or identity.
>  
> -- Berlant and Warner, "Sex in Public" (1998)

<!-- Queer communities exist and are worth studying.  -->

LGBTQ communities provide an interesting edge case for understanding the operation of community writ large. As Berlant and Warner's notion of queer counterpublics demonstrates, queer social worlds are fluid, heterogeneous, and complex; they have unique features that exceed the bounds of what might be recognizable as community. And yet, more down-to-earth ideas of community and identity are central to the experiences of many LGBTQ people. The emergence of queer spaces and the communities that inhabit them is improbable and surprising; their continued existence is contingent and fragile [@demilio_capitalism_1992; @berube_my_2011; @ghaziani_there_2014]. But enough people evidently want them to make them happen -- at first, in spite of stigma and oppression, and still, in spite of normative and assimilatory pressures. Even today, many LGBTQ people want distinctive spaces in which to build queer community and culture [@pew_research_center_survey_2013]. Because queer community can't be taken for granted, it's an ideal site for observing explicit processes of community.

<!-- Note: do I mean contingent on urbanization? maybe -->

Several aspects of LGBTQ communities make them interesting. One unique feature is a lack of rootedness, which shapes queer life trajectories: for the most part, LGBTQ people are not born into and do not grow up in queer communities and queer spaces [@weston_sexual_1995]. This is one reason that the existence and experience of queer community isn't something LGBTQ people can take for granted. I suspect that this is also one reason that surveys targeted toward LGBTQ people ask about community in detailed and explicit ways, where more general surveys often do not; the need for community is visible and salient in LGBTQ contexts. Similarly, this might be why LGBTQ people have sought out virtual communities since those spaces first came into being. 

<!-- Note: say something about cross-cutting identities and ties. -->

At the same time, LGBTQ identities are often strongly held and offer a strong basis for community formation. LGBTQ identity shapes attitudes toward sexuality, but also beliefs and values more broadly [@schnabel_sexual_2018]. LGBTQ identities are potentially encompassing enough to constitute a subculture [@fischer_toward_1975; @mattson_bar_2015] or a counterpublic [@berlant_sex_1998], leading theorists to write about gay culture [@halperin_how_2012] or a way of life [@foucault_friendship_1998]. Structurally speaking, the mere fact that gay/queer/LGBTQ community exists as a possible object of attachment and source of belonging is itself noteworthy; the identity itself structurally and cognitively provides a potential axis of belonging that isn't available otherwise. By contrast, the unmarked category of "heterosexual" isn't available as a source of community in the same way -- referring, for instance, to "members of the heterosexual community" is nonsensical [@zerubavel_taken_2018], even if many communities do have heteronormativity and heterosexuality as defining or central traits [@eliasoph_avoiding_1998].

<!-- Note: In other words, this ain't a soccer team or a parent-teacher association. Though, to be honest, I think "parent" can be one of those really encompassing identities/roles as well. -->

Queer communities are marked by their diversity and fluidity, by a proliferation of identities, expressions, practices, and ways of being. Due to processes of social sorting, this variation is not observable everywhere; some particular LGBTQ groups and spaces are more homogeneous and exclusionary, some more diverse and welcoming. Importantly, whether they embrace difference or exclude it, queer communities are not utopic and egalitarian; they're structured by inequalities of race, class, age, gender, embodiment, etc. [CITE: numerous]. In the most optimistic assessments, queer communites and queer spaces might offer ways to complicate or bridge class [@mattson_style_2015] or race [@orne_boystown_2017]; a more pessimistic take might be that other social structures present a fundamental obstacle to fully experiencing or building community. Regardless, anarchic, chaotic variation is a defining feature of the overarching LGBTQ community as a whole [@orne_boystown_2017; @brekhus_peacocks_2003; @mattson_style_2015; @brown-saracino_how_2017; @lichterman_talking_1999]. This variation might be thought to undermine community cohesion and lead to divisions, especially in the context of selective state recognition [@butler_bodies_2004]. But I would argue, and ultimately hope to show, that empirical reality is more complex than the most pessimistic predictions of queer theorists and activists -- namely, that the most normative and assimilable LGBTQ people will leave the rest behind. For example, how much solidarity is there between cisgender LGBQ people and trans people, in the current moment of anti-trans activism and legislation? Far more than none, but perhaps still not enough. @lichterman_talking_1999 once argued for "flexible forms of solidarity that sustain both unities and particularities," as essential for a multicultural democracies; I would argue that queer communities furnish an important example of that possibility. As political communities that are less stable and unitary, and more fluid or heterogeneous, they show how to facilitate both a sense of group belonging and the capacity for collective action, while incorporating democratic notions of freedom [@butler_undoing_2004].

<!-- Note: adapted from one of my comprehensive exam essays. -->

I would not argue that the LGBTQ case is completely unique. In some ways, LGBTQ people might be similar to people who hold other marginalized and minoritized identities: shared experiences of social marginalization, stigma, and discrimination, or even the experience of being a numeric minority; all factors which could heighten the perceived need for community, affecting what it means and how it can be created. Those analytic features are important, but I don't aim to use them to draw analogies between, say, sexuality and race (i.e., between the experiences of LGBTQ people and people of color). A key reason researchers are reluctant to analogize in that way is that people of course simultaneously hold multiple social identities, or occupy multiple social positions, and those identities can interact in complex ways. To translate that identity-oriented frame into terms of community and belonging, it's very likely that queer people of color find their ability to experience belonging in queer spaces to be mediated by race [@held_they_2017], and in communities of color mediated by sexuality. In any case, stigma and exclusion in heteronormative spaces operate as a push factor in tandem with the attractive pull of queer community, to explain why and how LGBTQ people come to seek out queer spaces. Variation on both of those fronts shapes how LGBTQ individuals experience connection to and participation in LGBTQ community.

Examining different ways queer community can play out across distinct geographic, temporal, and technological settings is how I might aim to triangulate around the concept of community. For some of the projects I propose below, a generic counterpart may provide a means of comparison; in other cases, internal variation might be adequate.

#### Method

My methodological approach is quantitative and computational. It's oriented toward synthesis, and aimed at complementing prior work on queer communities, and about community more broadly. This prior work is primarily qualitative, and I think there's space to try something different. I'll combine techniques for text, spatial, and network data analysis with conventional methods, and draw on the advantages of quantitative methods for studying variation. This also plays to the strengths of my training. What I'm offering here by taking a computational and quantitative approach to community is a different angle -- not necessarily a better one, but hopefully a complementary one, and one that I'm uniquely positioned to undertake. 
